// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTJjAZ7KIWuLj80eY8Is3EHL7rALf718k',
    appId: '1:1039089780901:ios:f5adf04d834fbc9de9254c',
    messagingSenderId: '1039089780901',
    projectId: 'trackmate-admin',
    storageBucket: 'trackmate-admin.firebasestorage.app',
    iosBundleId: 'com.example.trackmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTJjAZ7KIWuLj80eY8Is3EHL7rALf718k',
    appId: '1:1039089780901:ios:f5adf04d834fbc9de9254c',
    messagingSenderId: '1039089780901',
    projectId: 'trackmate-admin',
    storageBucket: 'trackmate-admin.firebasestorage.app',
    iosBundleId: 'com.example.trackmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_Vx26eZHmerZYCC9F1OKHkynhG18RWhk',
    appId: '1:1039089780901:web:a221af3c7e282d4ae9254c',
    messagingSenderId: '1039089780901',
    projectId: 'trackmate-admin',
    authDomain: 'trackmate-admin.firebaseapp.com',
    storageBucket: 'trackmate-admin.firebasestorage.app',
    measurementId: 'G-1NWHSNXRR2',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_Vx26eZHmerZYCC9F1OKHkynhG18RWhk',
    appId: '1:1039089780901:web:6a722fd989d9dcd7e9254c',
    messagingSenderId: '1039089780901',
    projectId: 'trackmate-admin',
    authDomain: 'trackmate-admin.firebaseapp.com',
    storageBucket: 'trackmate-admin.firebasestorage.app',
    measurementId: 'G-6VQ9P4HLN9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxkTjAzBbASn0-k3PyWBWaTrnGXSyohi4',
    appId: '1:1039089780901:android:4bf876d1173c5945e9254c',
    messagingSenderId: '1039089780901',
    projectId: 'trackmate-admin',
    storageBucket: 'trackmate-admin.firebasestorage.app',
  );

}